/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_HelloJNI */

#ifndef _Included_com_jni_HelloJNI
#define _Included_com_jni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_HelloJNI
 * Method:    getInstance
 * Signature: ()Lcom/jni/HelloJNI;
 */
JNIEXPORT jobject JNICALL Java_com_jni_HelloJNI_getInstance
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_HelloJNI
 * Method:    modifyField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_HelloJNI_modifyField
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
